// "Help me adjust today": the rules, checked on the app's own code (bundled for Node from app/src/ai and app/src/data
// by ai-eval/build.mjs), with made-up data in memory only. No browser, no network, no real records.
//   [1] what's sent (context)  [2] every rule on a reply  [3] saving: only after confirming, never stale, undo
//   [4] the instructions and the mock planner  [5] the model adapter (with a fake provider)
process.env.TZ = 'Europe/London';
const path = require('path');
const os = require('os');
const { pathToFileURL } = require('url');
const { check, summary } = require('./cdp.js');
const ROOT = process.env.MYDAY_ROOT || path.resolve(__dirname, '..');
const eq = (a, b) => JSON.stringify(a) === JSON.stringify(b);

(async () => {
  const { bundle } = await import(pathToFileURL(path.join(ROOT, 'ai-eval/build.mjs')).href);
  const K = await import(pathToFileURL(await bundle(path.join(ROOT, 'ai-eval/kit.ts'), path.join(os.tmpdir(), `myday-aikit-${process.pid}`))).href);
  K.useMemoryStorage();
  const task = (uid, title, category, minutes, x = {}) => ({ uid, taskId: 'l-' + uid, category, title, minutes, baseMinutes: minutes, done: false, shrunk: false, fromQueue: null, rolledQid: null, scheduledStart: null, scheduledEnd: null, ...x });
  // A day at a given time, built from the app's defaults (and saved to the memory-only storage).
  function day(now, energy, tasks, more = () => {}) {
    K.setClock(now);
    const k = now.slice(0, 10), s = K.freshState();
    s.days[k] = { energy, rest: false, builtAt: k + 'T08:00', checkedIn: false, tasks };
    if (energy !== null) s.context[k] = { energy, sleep: { start: null, end: null, estimatedHours: 7 } };
    more(s, k);
    localStorage.clear(); localStorage.setItem('myday.data.v4', JSON.stringify(s)); K.boot();
    return { k, data: K.getSnapshot().data };
  }
  const reply = o => JSON.stringify({ rest: false, priorities: [], explanation: 'Gently does it.', missing: [], ...o });
  const pr = (taskId, minutes, start = null) => ({ taskId, minutes, start });
  const codes = r => r.violations.map(v => v.code);
  const D = '2026-11-10';
  const THREE = () => [task('a', 'Course section', 'learning', 30), task('b', 'Batch cook', 'admin', 45), task('c', 'Gym', 'health', 60)];
  const NIGHT = (s, anchor) => { s.rota.patterns = [{ id: 'p1', effectiveFrom: null, anchor, cycle: ['night', 'off'], times: { day: { start: '07:00', end: '19:00' }, night: { start: '19:00', end: '07:00' } }, breaks: { day: 30, night: 30 } }]; };
  const DAYSHIFT = s => { s.rota.patterns = [{ id: 'p1', effectiveFrom: null, anchor: D, cycle: ['day'], times: { day: { start: '07:00', end: '19:00' }, night: { start: '19:00', end: '07:00' } }, breaks: { day: 30, night: 30 } }]; };

  console.log('\n[1] What is sent (gathered by the app)');
  let { k, data } = day(`${D}T09:30`, 3, THREE(), s => { s.commitments.push({ id: 'c1', kind: 'appointment', title: 'Dentist — Dr Smith', start: `${D}T11:00`, end: `${D}T12:00` }); });
  let ctx = K.buildContext(data, k, '  I slept badly and only have 20 minutes  ' + 'x'.repeat(300));
  check('the current date, time, weekday and time zone', ctx.date === D && ctx.now === '09:30' && ctx.weekday === 'Tuesday' && ctx.timezone === 'Europe/London', [ctx.date, ctx.now, ctx.weekday, ctx.timezone]);
  check('energy, the energy rule (energy 3 → 2 tasks) and the plan\'s tasks with their ids', ctx.energy === 3 && ctx.maxPriorities === 2 && !ctx.smallOnly && eq(ctx.tasks.map(t => t.id), ['a', 'b', 'c']));
  check('appointments as busy time, without their names', ctx.busy.some(b => b.kind === 'appointment' && b.start === `${D}T11:00`) && !JSON.stringify(ctx).includes('Dentist') && !JSON.stringify(ctx).includes('Smith'));
  check('free time leaves out the appointment and its prep/travel time (30 min either side)', eq(ctx.free, [{ start: '09:30', end: '10:30' }, { start: '12:30', end: '21:00' }]), ctx.free);
  check('your note, trimmed and kept short (200 characters)', ctx.note.startsWith('I slept badly') && ctx.note.length === 200);
  check('nothing from other sections (no Finance, Health records or Study notes)', !('finance' in ctx) && !('health' in ctx) && typeof ctx.revisionDue === 'number');
  ({ k, data } = day(`${D}T10:00`, 2, THREE(), s => NIGHT(s, '2026-11-09')));
  ctx = K.buildContext(data, k, '');
  check('last night\'s shift (19:00–07:00) is included, crossing midnight', ctx.busy.some(b => b.kind === 'work' && b.start === '2026-11-09T19:00' && b.end === `${D}T07:00`), ctx.busy);
  ({ k, data } = day('2026-10-25T08:00', 2, THREE(), s => NIGHT(s, '2026-10-24')));
  ctx = K.buildContext(data, k, '');
  check('the night the clocks go back: the shift still ends at 07:00 (it\'s 13 hours), and free time starts after prep/travel at 07:30', ctx.busy.some(b => b.kind === 'work' && b.end === '2026-10-25T07:00') && ctx.free[0].start === '08:00', [ctx.busy, ctx.free]);
  for (const [e, n, small] of [[1, 1, true], [2, 1, true], [3, 2, false], [4, 3, false], [5, 3, false], [null, 1, true]]) {
    ({ k, data } = day(`${D}T09:00`, e, THREE()));
    ctx = K.buildContext(data, k, '');
    check(`energy ${e === null ? 'not recorded' : e}: room for ${n}${small ? ', small only' : ''}`, ctx.maxPriorities === n && ctx.smallOnly === small);
  }
  ({ k, data } = day(`${D}T11:00`, 3, [task('a', 'Course', 'learning', 30, { done: true }), task('b', 'Cook', 'admin', 45), task('c', 'Gym', 'health', 60)]));
  check('energy 3 with one task done: room for one more (as Review my plan counts it)', K.buildContext(data, k, '').maxPriorities === 1);
  ({ k, data } = day(`${D}T09:00`, null, THREE(), s => { delete s.context[D]; }));
  check('missing information is named, not guessed (energy and sleep)', eq(K.missingInfo(data, k), ["Today's energy isn't recorded, so the suggestion stays small.", "Last night's sleep isn't recorded."]));

  console.log('\n[2] Every reply is checked against MyDay\'s rules');
  ({ k, data } = day(`${D}T09:00`, 1, THREE()));
  let r = K.checkProposal(reply({ priorities: [pr('a', 30), pr('b', 45), pr('c', 60)] }), data, k);
  check('energy 1: three suggested → one kept, and kept small (30 → 20 min)', r.proposal.priorities.length === 1 && r.proposal.priorities[0].minutes === 20 && codes(r).includes('too-many') && codes(r).includes('not-small'), [codes(r), r.proposal.priorities]);
  check('…and it says why, in plain words', r.proposal.adjusted.some(a => a.includes('energy 1')) && r.proposal.adjusted.some(a => a.includes('shortened to 20 minutes')));
  ({ k, data } = day(`${D}T09:00`, 2, THREE()));
  r = K.checkProposal(reply({ priorities: [pr('a', 15), pr('b', 15)] }), data, k);
  check('energy 2: at most one small task', r.proposal.priorities.length === 1 && codes(r).includes('too-many'));
  ({ k, data } = day(`${D}T09:00`, 3, THREE()));
  r = K.checkProposal(reply({ priorities: [pr('a', 30), pr('b', 45), pr('c', 60)] }), data, k);
  check('energy 3: at most two', r.proposal.priorities.length === 2 && codes(r).includes('too-many'));
  ({ k, data } = day(`${D}T09:00`, 5, THREE()));
  r = K.checkProposal(reply({ priorities: [pr('a', 30), pr('b', 45), pr('c', 60)] }), data, k);
  check('energy 5: three is fine', r.proposal.priorities.length === 3 && r.violations.length === 0, codes(r));
  ({ k, data } = day(`${D}T09:00`, null, THREE(), s => { delete s.context[D]; }));
  r = K.checkProposal(reply({ priorities: [pr('a', 30), pr('b', 45)] }), data, k);
  check('energy not recorded: treated as unknown — one small task, and the missing information shown', r.proposal.priorities.length === 1 && r.proposal.priorities[0].minutes === 20 && r.proposal.missing.some(m => m.includes('energy')));
  ({ k, data } = day(`${D}T09:00`, 4, [task('a', 'Course', 'learning', 30, { done: true }), task('b', 'Cook', 'admin', 45), task('c', 'Gym', 'health', 60)]));
  r = K.checkProposal(reply({ priorities: [pr('x-made-up', 30), pr('a', 30), pr('b', 45), pr('b', 30)] }), data, k);
  check('tasks that aren\'t on the plan, are already done, or repeat are dropped', r.proposal.priorities.length === 1 && r.proposal.priorities[0].uid === 'b' && ['unknown-task', 'done-task', 'repeated-task'].every(c => codes(r).includes(c)), codes(r));
  r = K.checkProposal(reply({ priorities: [pr('b', 120), pr('c', 2)] }), data, k);
  check('never longer than the task\'s usual length (120 → 45), never under 5 minutes', r.proposal.priorities[0].minutes === 45 && r.proposal.priorities[1].minutes === 5 && codes(r).includes('too-long') && codes(r).includes('too-short'));
  ({ k, data } = day(`${D}T06:00`, 4, THREE(), s => { DAYSHIFT(s); s.settings.earliestTime = '05:30'; }));
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '12:00'), pr('b', 20, '06:00')] }), data, k);
  check('a time on top of a shift is removed (with the reason); a time that fits is kept', r.proposal.priorities[0].start === null && r.proposal.priorities[1].start === 360 && codes(r).includes('time-conflict') && /Day shift \(07:00–19:00\)/.test(r.violations.find(v => v.code === 'time-conflict').detail), r.violations);
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '06:15')] }), data, k);
  check('…and one that would run into the prep/travel time before it', r.proposal.priorities[0].start === null && codes(r).includes('time-conflict'));
  ({ k, data } = day(`${D}T06:00`, 3, THREE(), s => NIGHT(s, '2026-11-09')));
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '06:30')] }), data, k);
  check('overnight: a time before last night\'s shift has ended (06:30) is removed', r.proposal.priorities[0].start === null && codes(r).includes('time-conflict'));
  ({ k, data } = day('2026-10-25T07:00', 3, THREE(), s => NIGHT(s, '2026-10-24')));
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '07:15'), pr('b', 20, '08:00')] }), data, k);
  check('the night the clocks go back: 07:15 clashes with the 13-hour shift\'s end, 08:00 is fine', r.proposal.priorities[0].start === null && r.proposal.priorities[1].start === 480, r.proposal.priorities);
  ({ k, data } = day(`${D}T20:00`, 4, THREE(), s => { s.settings.latestTime = '23:30'; s.context['2026-11-11'] = { energy: null, sleep: { start: `${D}T22:00`, end: '2026-11-11T06:00', estimatedHours: null } }; }));
  r = K.checkProposal(reply({ priorities: [pr('c', 60, '21:30'), pr('a', 30, '20:30')] }), data, k);
  check('recorded sleep tonight (from 22:00) is respected: 21:30 for an hour is removed, 20:30 kept', r.proposal.priorities[0].start === null && r.proposal.priorities[1].start === 1230 && /sleep/i.test(r.violations[0].detail), r.violations);
  ({ k, data } = day(`${D}T14:00`, 4, THREE()));
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '09:00'), pr('b', 45, '15:00'), pr('c', 60, '15:30')] }), data, k);
  check('times in the past, and two suggestions on top of each other, are removed', r.proposal.priorities[0].start === null && r.proposal.priorities[1].start === 900 && r.proposal.priorities[2].start === null, r.proposal.priorities.map(p => p.start));
  r = K.checkProposal(reply({ priorities: [pr('a', 30, '9am')] }), data, k);
  check('a time that isn\'t a time is removed', r.proposal.priorities[0].start === null && codes(r).includes('bad-time'));
  r = K.checkProposal(reply({ rest: true }), data, k);
  check('rest is always allowed (and then everything open waits)', r.proposal.rest && r.violations.length === 0 && r.proposal.later.length === 3);
  r = K.checkProposal(reply({ rest: true, priorities: [pr('a', 30)] }), data, k);
  check('rest with tasks alongside: rest wins (the gentler reading)', r.proposal.rest && r.proposal.priorities.length === 0 && codes(r).includes('rest-and-tasks'));
  r = K.checkProposal('Sure! Here is a plan: do the laundry.', data, k);
  check('a reply that isn\'t JSON gives no suggestion at all', r.proposal === null && codes(r)[0] === 'not-json');
  r = K.checkProposal('```json\n' + reply({ priorities: [pr('a', 30)] }) + '\n```', data, k);
  check('JSON wrapped in ``` fences is still read', !!r.proposal && r.proposal.priorities.length === 1);
  r = K.checkProposal(JSON.stringify({ priorities: 'all of them', explanation: 3 }), data, k);
  check('the wrong shape gives no suggestion', r.proposal === null && codes(r)[0] === 'bad-shape');
  r = K.checkProposal(reply({ explanation: 'You should really push through and not fall behind.' }), data, k);
  check('pushy or guilt-tripping wording is replaced with a gentle explanation', codes(r).includes('pressure-language') && !/should|behind/.test(r.proposal.explanation), r.proposal.explanation);
  r = K.checkProposal(reply({ explanation: Array.from({ length: 80 }, (_, i) => 'word' + i).join(' ') + '.' }), data, k);
  check('long explanations are shortened (at most 45 words)', codes(r).includes('long-explanation') && r.proposal.explanation.split(' ').length <= 45);
  r = K.checkProposal(reply({ missing: ['How much time you have', 7, ''] }), data, k);
  check('missing information from the model is kept (only sensible text)', eq(r.proposal.missing, ['How much time you have']));
  ({ k, data } = day(`${D}T11:00`, 2, [], s => { s.days[D] = { energy: 2, rest: true, builtAt: '', checkedIn: false, tasks: [] }; }));
  r = K.checkProposal(reply({ priorities: [pr('a', 10)] }), data, k);
  check('a rest day stays a rest day', r.proposal.rest && r.proposal.priorities.length === 0);

  console.log('\n[3] Saving: only after you confirm, never stale, and one step of undo');
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45, { scheduledStart: `${D}T12:00`, scheduledEnd: `${D}T12:45` }), task('c', 'Gym', 'health', 60)], s => { s.days['2026-11-09'] = { energy: 4, rest: false, builtAt: '', checkedIn: true, tasks: [task('z', 'Old', 'admin', 20, { done: true })] }; }));
  const before = JSON.parse(localStorage.getItem('myday.data.v4'));
  const stamp = K.planStamp(K.getSnapshot().data, k);
  r = K.checkProposal(reply({ priorities: [pr('c', 25, '10:00'), pr('a', 20, null)] }), K.getSnapshot().data, k);
  check('checking a reply saves nothing', eq(JSON.parse(localStorage.getItem('myday.data.v4')), before));
  let res = K.applyAi(k, stamp, r.proposal);
  let after = JSON.parse(localStorage.getItem('myday.data.v4'));
  const t = uid => after.days[k].tasks.find(x => x.uid === uid);
  check('using it saves through the checked save path', res.ok && after.saves.seq === before.saves.seq + 1);
  check('the priorities first, with the suggested minutes and time', eq(after.days[k].tasks.map(x => x.uid), ['c', 'a']) && t('c').minutes === 25 && t('c').scheduledStart === `${D}T10:00` && t('a').minutes === 20 && t('a').scheduledStart === null);
  check('…the task\'s usual length (its template) is unchanged', t('c').baseMinutes === 60 && t('a').baseMinutes === 30);
  check('…the task lists, other days and the energy rating are untouched', eq(after.lists, before.lists) && eq(after.days['2026-11-09'], before.days['2026-11-09']) && after.days[k].energy === 3 && eq(after.context, before.context));
  check('…and the task left out waits in the queue (nothing deleted)', after.queue.some(q => q.title === 'Cook'));
  res = K.undoAi(res.undo);
  check('Undo puts the plan and the queue back exactly', res === 'undone' && eq(JSON.parse(localStorage.getItem('myday.data.v4')).days, before.days) && eq(JSON.parse(localStorage.getItem('myday.data.v4')).queue, before.queue));
  // Stale: the plan changes after asking.
  const s2 = K.planStamp(K.getSnapshot().data, k);
  K.update(d => { d.days[k].tasks[0].done = true; });
  const snap = localStorage.getItem('myday.data.v4');
  res = K.applyAi(k, s2, r.proposal);
  check('a suggestion made before a task was ticked is refused ("stale") and nothing is saved', !res.ok && res.reason === 'stale' && localStorage.getItem('myday.data.v4') === snap);
  for (const [what, change] of [['energy changed', d => { d.context[k].energy = 1; }], ['an appointment was added', d => { d.commitments.push({ id: 'c9', kind: 'appointment', title: 'x', start: `${D}T15:00`, end: `${D}T16:00` }); }], ['tonight\'s sleep was recorded', d => { d.context['2026-11-11'] = { energy: null, sleep: { start: `${D}T22:00`, end: '2026-11-11T06:00', estimatedHours: null } }; }]]) {
    const st = K.planStamp(K.getSnapshot().data, k);
    K.update(change);
    check(`…also when ${what}`, K.applyAi(k, st, r.proposal).reason === 'stale');
  }
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ priorities: [pr('a', 20)] }), data, k);
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  K.update(d => { d.days[k].tasks[0].done = true; });
  check('Undo is refused once the plan has changed since (nothing is overwritten)', K.undoAi(res.undo) === 'changed' && JSON.parse(localStorage.getItem('myday.data.v4')).days[k].tasks[0].done === true);
  // Another device: its change reaches this browser through sync, saved by another tab (this tab hasn't seen it yet).
  const otherTab = change => { const o = JSON.parse(localStorage.getItem('myday.data.v4')); change(o); o.saves = { ...o.saves, seq: o.saves.seq + 1 }; localStorage.setItem('myday.data.v4', JSON.stringify(o)); };
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ priorities: [pr('a', 20)] }), data, k);
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  otherTab(o => { o.days[k].tasks[0].done = true; });
  let theirs = localStorage.getItem('myday.data.v4');
  check('Undo after another device ticked a task on today\'s plan: refused ("changed"), and their change is kept', K.undoAi(res.undo) === 'changed' && localStorage.getItem('myday.data.v4') === theirs && K.getSnapshot().data.days[k].tasks[0].done === true);
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ priorities: [pr('a', 20)] }), data, k);
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  otherTab(o => { o.days['2026-11-20'] = { energy: 4, rest: false, builtAt: '', checkedIn: true, tasks: [task('y', 'Planned on the phone', 'admin', 20)] }; });
  const undone = K.undoAi(res.undo);
  after = JSON.parse(localStorage.getItem('myday.data.v4'));
  check('Undo after another device changed something else (another day): today\'s plan goes back, and their change is kept', undone === 'undone' && after.days['2026-11-20'] && after.days['2026-11-20'].tasks[0].title === 'Planned on the phone' && eq(after.days[k].tasks.map(x => x.uid), ['a', 'b']) && after.days[k].tasks[0].minutes === 30, undone);
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ priorities: [pr('a', 20)] }), data, k);
  const st0 = K.planStamp(data, k);
  otherTab(o => { o.context[k].energy = 1; });
  theirs = localStorage.getItem('myday.data.v4');
  res = K.applyAi(k, st0, r.proposal);
  check('Using a suggestion after another device changed today\'s energy: refused ("stale"), their change kept', !res.ok && res.reason === 'stale' && localStorage.getItem('myday.data.v4') === theirs);
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ rest: true }), data, k);
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  check('rest: today becomes a rest day (as "Swap for a rest day" does), energy kept', res.ok && K.getSnapshot().data.days[k].rest && K.getSnapshot().data.days[k].energy === 3);
  ({ k, data } = day(`${D}T09:00`, 3, [task('a', 'Course', 'learning', 30, { done: true }), task('b', 'Cook', 'admin', 45)]));
  r = K.checkProposal(reply({ rest: true }), data, k);
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  check('rest with something already done: the done task stays, the rest waits in the queue', res.ok && !K.getSnapshot().data.days[k].rest && K.getSnapshot().data.days[k].tasks.length === 1 && K.getSnapshot().data.queue.some(q => q.title === 'Cook'));
  ({ k, data } = day(`${D}T09:00`, 3, THREE()));
  r = K.checkProposal(reply({ priorities: [pr('a', 20)] }), data, k);
  const saved = localStorage.getItem('myday.data.v4');
  const realSet = localStorage.setItem;
  localStorage.setItem = () => { throw new Error('QuotaExceededError'); };
  res = K.applyAi(k, K.planStamp(data, k), r.proposal);
  localStorage.setItem = realSet;
  check('if the browser can\'t save (storage full), it says so and nothing changes', !res.ok && res.reason === 'not-saved' && localStorage.getItem('myday.data.v4') === saved && K.getSnapshot().data.days[k].tasks.length === 3);
  K.boot();
  check('after a reload (start-up), the saved plan is exactly what was saved', localStorage.getItem('myday.data.v4') === saved);

  console.log('\n[4] The instructions and the mock planner');
  ({ k, data } = day(`${D}T09:00`, 2, THREE()));
  ctx = K.buildContext(data, k, 'I slept badly');
  const msgs = K.buildMessages(ctx);
  check('one system message with the rules, then the context as JSON (date, time zone, note)', msgs.length === 2 && /maxPriorities/.test(msgs[0].content) && /Rest is always a valid choice/.test(msgs[0].content) && msgs[1].content.includes('"timezone":"Europe/London"') && msgs[1].content.includes('I slept badly'));
  const good = K.checkProposal(K.mockPlanner(ctx, 'good'), data, k);
  check('the mock planner follows the rules', good.violations.length === 0 && good.proposal.priorities.length === 1 && good.proposal.priorities[0].minutes <= 20);
  const sloppy = K.checkProposal(K.mockPlanner(ctx, 'sloppy'), data, k);
  check('its rule-breaking version is caught on every count', ['too-many', 'unknown-task', 'too-long', 'pressure-language'].every(c => codes(sloppy).includes(c)) && sloppy.proposal.priorities.length === 1, codes(sloppy));
  check('…and its non-JSON version gives no suggestion', K.checkProposal(K.mockPlanner(ctx, 'invalid'), data, k).proposal === null);

  console.log('\n[5] The model adapter (a fake provider; no network)');
  const seen = [];
  const fake = (status, body, delay = 0) => async (url, init) => { seen.push({ url, init }); await new Promise(r => setTimeout(r, delay)); if (init.signal.aborted) throw Object.assign(new Error('aborted'), { name: 'AbortError' }); return new Response(typeof body === 'string' ? body : JSON.stringify(body), { status }); };
  const cfg = { provider: 'openai-compatible', label: 'Test', model: 'test-model', baseUrl: 'https://provider.example/v1/', apiKey: 'sk-test', temperature: 0.2, maxOutputTokens: 300, timeoutMs: 200, extraBody: { enable_thinking: false }, priceInPerMTok: 0.4, priceOutPerMTok: 1.2 };
  let m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) } }], usage: { prompt_tokens: 900, completion_tokens: 40 } }));
  const req0 = JSON.parse(seen[0].init.body);
  check('an OpenAI-style request: the model, the two messages, JSON output, a length cap and model-specific fields', seen[0].url === 'https://provider.example/v1/chat/completions' && req0.model === 'test-model' && req0.messages.length === 2 && req0.response_format.type === 'json_object' && req0.max_tokens === 300 && req0.enable_thinking === false);
  check('the key goes only in the Authorization header', seen[0].init.headers.Authorization === 'Bearer sk-test' && !seen[0].init.body.includes('sk-test'));
  check('the reply text and token counts come back; the cost is worked out from the prices', m.ok && m.inputTokens === 900 && m.outputTokens === 40 && Math.abs(K.costUsd(cfg, 900, 40) - (900 * 0.4 + 40 * 1.2) / 1e6) < 1e-12);
  check('a worst-case cost can be worked out before calling (for the budget)', K.worstCaseCostUsd(cfg, ctx) > 0 && K.worstCaseCostUsd({ ...cfg, priceInPerMTok: null }, ctx) === null);
  m = await K.callModel(cfg, ctx, fake(500, 'oops'));
  check('a server error is reported (no reply text)', !m.ok && m.error === 'http' && m.status === 500);
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: '' } }] }));
  check('an empty reply is reported', !m.ok && m.error === 'empty');
  m = await K.callModel(cfg, ctx, fake(200, {}, 400));
  check('a slow provider is cut off at the time limit', !m.ok && m.error === 'timeout');
  const cut = reply({ priorities: [pr('a', 20)] }).slice(0, 40);
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: cut }, finish_reason: 'length' }], usage: { prompt_tokens: 900, completion_tokens: 300 } }));
  check('a reply cut off at the length limit (finish_reason "length"): unsuccessful, no text — its billed tokens still reported', !m.ok && m.error === 'truncated' && !('text' in m) && m.outputTokens === 300 && m.finishReason === 'length');
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: cut }, finish_reason: 'model_context_window_exceeded' }] }));
  check('…also when the context window ran out (Z.ai)', !m.ok && m.error === 'truncated');
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) }, finish_reason: 'sensitive' }] }));
  check('a filtered reply (finish_reason "sensitive" / "content_filter"): unsuccessful', !m.ok && m.error === 'filtered' && !(await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) }, finish_reason: 'content_filter' }] }))).ok);
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) }, finish_reason: 'network_error' }] }));
  check('a provider-side failure (finish_reason "network_error"): unsuccessful', !m.ok && m.error === 'network');
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) }, finish_reason: 'tool_calls' }] }));
  check('any other finish (e.g. "tool_calls"): unsuccessful', !m.ok && m.error === 'incomplete');
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: '', reasoning_content: 'Thinking about the plan…' }, finish_reason: 'stop' }], usage: { prompt_tokens: 900, completion_tokens: 120, completion_tokens_details: { reasoning_tokens: 120 } } }));
  check('reasoning but an empty final answer: unsuccessful ("empty"), with the reasoning tokens reported', !m.ok && m.error === 'empty' && m.reasoningTokens === 120 && m.outputTokens === 120);
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: reply({}) }, finish_reason: 'stop' }], usage: { prompt_tokens: 900, completion_tokens: 40, total_tokens: 1100, completion_tokens_details: { reasoning_tokens: 160 } } }));
  check('reasoning tokens are reported, and billed output is never less than the total says', m.ok && m.reasoningTokens === 160 && m.outputTokens === 200 && m.finishReason === 'stop');
  m = await K.callModel(cfg, ctx, fake(200, { choices: [{ message: { content: cut }, finish_reason: 'stop' }] }));
  const half = K.checkProposal(m.text, data, k);
  check('JSON that stops half-way (even with "stop"): no suggestion, so nothing can be saved', m.ok && half.proposal === null && half.violations[0].code === 'not-json');
  m = await K.callModel(cfg, ctx, fake(400, { error: { code: 'InvalidParameter', message: 'max_completion_tokens is not supported; key sk-test rejected', type: 'invalid_request_error' } }));
  check('a refused request: the provider\'s message is kept (to diagnose it), with the key blanked out', !m.ok && m.error === 'http' && m.status === 400 && /InvalidParameter/.test(m.detail) && /max_completion_tokens/.test(m.detail) && !m.detail.includes('sk-test'), m.detail);
  m = await K.callModel({ ...cfg, apiKey: '' }, ctx, fake(200, {}));
  check('without a key, nothing is sent', !m.ok && m.error === 'config');
  await K.callModel({ ...cfg, maxTokensField: 'max_completion_tokens' }, ctx, fake(200, { choices: [{ message: { content: reply({}) } }] }));
  let b = JSON.parse(seen[seen.length - 1].init.body);
  check('Qwen-style: the reply cap as max_completion_tokens, thinking off', b.max_completion_tokens === 300 && !('max_tokens' in b) && b.enable_thinking === false);
  check('…and the instructions mention JSON (Qwen needs that for JSON output)', /JSON/.test(K.SYSTEM_PROMPT));
  await K.callModel({ ...cfg, jsonMode: false, extraBody: { thinking: { type: 'enabled' }, reasoning_effort: 'low' }, maxOutputTokens: 2048 }, ctx, fake(200, { choices: [{ message: { content: reply({}) } }] }));
  b = JSON.parse(seen[seen.length - 1].init.body);
  check('GLM-style: thinking kept on at low effort, a bigger cap, JSON mode can be left off', b.thinking.type === 'enabled' && b.reasoning_effort === 'low' && b.max_tokens === 2048 && !('response_format' in b));

  console.log('\n[6] The evaluation: live runs only on purpose, within budget, and no keys in the results');
  const run = await import(pathToFileURL(await bundle(path.join(ROOT, 'ai-eval/run.ts'), path.join(os.tmpdir(), `myday-aieval-${process.pid}`))).href);
  const fails = async fn => { try { await fn(); return ''; } catch (e) { return e.message; } };
  let calls = 0;
  const fakeProvider = require('http').createServer((req, res) => {
    let b = '';
    req.on('data', c => { b += c; });
    req.on('end', () => {
      calls++;
      const c = JSON.parse(JSON.parse(b).messages[1].content.replace(/^[^\n]*\n/, ''));
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ choices: [{ message: { content: K.mockPlanner(c, 'good') } }], usage: { prompt_tokens: 1000, completion_tokens: 50 } }));
    });
  });
  await new Promise(r => fakeProvider.listen(0, '127.0.0.1', r));
  const fakeModel = { label: 'Fake provider', provider: 'openai-compatible', model: 'fake-1', baseUrl: `http://127.0.0.1:${fakeProvider.address().port}`, keyEnv: 'FAKE_KEY', priceInPerMTok: 100, priceOutPerMTok: 100, maxOutputTokens: 300 };
  const base = { modelIds: ['fake'], repeats: 3, scenarioIds: null, env: { FAKE_KEY: 'secret-key-123' }, models: { fake: fakeModel }, log: () => {} };
  check('a real model is never called without --live', /add --live/.test(await fails(() => run.evaluate({ ...base, live: false, budgetUsd: 1 }))));
  check('…or without a budget', /needs a budget/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: null }))));
  check('…or without its key in the environment', /needs its key/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: 1, env: {} }))));
  check('…or without prices (so the budget can be enforced)', /needs its prices/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: 1, models: { fake: { ...fakeModel, priceOutPerMTok: null } } }))));
  const ws = { ...fakeModel, baseUrl: fakeModel.baseUrl + '/{WorkspaceId}', urlVars: { WorkspaceId: 'FAKE_WS' } };
  check('…or without the workspace id its address needs', /FAKE_WS/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: 1, models: { fake: ws } }))));
  let lastPath = '';
  fakeProvider.on('request', req => { lastPath = req.url; });
  await run.evaluate({ ...base, live: true, budgetUsd: 0.2, repeats: 1, scenarioIds: ['s01-energy-1'], models: { fake: ws }, env: { FAKE_KEY: 'secret-key-123', FAKE_WS: 'ws-123' } });
  check('the workspace id fills in the address', lastPath === '/ws-123/chat/completions', lastPath);
  await run.evaluate({ ...base, live: true, budgetUsd: 0.2, repeats: 1, scenarioIds: ['s01-energy-1'], models: { fake: { ...ws, baseUrlEnv: 'FAKE_BASE' } }, env: { FAKE_KEY: 'secret-key-123', FAKE_BASE: fakeModel.baseUrl + '/shared' } });
  check('…or a whole address from the environment replaces it (then no workspace id is needed)', lastPath === '/shared/chat/completions', lastPath);
  calls = 0;
  const live = await run.evaluate({ ...base, live: true, budgetUsd: 0.5 });
  check('an expensive (fake) model: the run stops before going over its budget', live.meta.stoppedForBudget && live.meta.spentUsd <= 0.5 && live.runs.some(r => r.outcome === 'skipped-budget') && calls === live.runs.filter(r => r.outcome !== 'skipped-budget').length, live.meta);
  const all = JSON.stringify(live) + run.summary(live) + run.review(live);
  check('the results hold no key and no prompt (only made-up scenario content and numbers)', !all.includes('secret-key-123') && !all.includes('Rules (the app checks'));
  check('no call is retried: one request per scenario, model and repeat', live.meta.retries === 0 && calls === live.runs.filter(x => x.reservedUsd !== null).length);
  check('unknown scenario names are refused (no silent empty run)', /Unknown scenario "s99"/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: 1, scenarioIds: ['s99'] }))));
  // A total ceiling across runs, from the ledger of earlier calls.
  const cheap = { ...fakeModel, priceInPerMTok: 0.4, priceOutPerMTok: 1.6, maxOutputTokens: 600 };
  const ledger = [];
  calls = 0;
  let tr = await run.evaluate({ ...base, live: true, repeats: 1, scenarioIds: ['s04-good-day', 's08-after-night-shift'], budgetUsd: 0.05, totalBudgetUsd: 0.5, spentBeforeUsd: 0, models: { fake: cheap }, onCall: c => ledger.push(c) });
  check('each live call goes in the ledger as it happens: set aside before, counted after (the cost estimated from reported token usage)', ledger.length === 2 && calls === 2 && ledger.every(c => c.counted === 'usage' && c.countedUsd > 0 && c.countedUsd <= c.reservedUsd && c.model === 'fake'), ledger);
  const sum0 = run.summary(tr);
  check('the report says "estimated cost from reported token usage" (never "actual" spending)', /Estimated cost from reported token usage/.test(sum0) && !/actual(ly)? (cost|spen)/i.test(sum0 + run.calls(tr)) && tr.meta.usageUsd > 0 && tr.meta.reservedUsd === 0);
  const one = ledger[0].reservedUsd;
  calls = 0;
  tr = await run.evaluate({ ...base, live: true, repeats: 1, scenarioIds: ['s04-good-day', 's08-after-night-shift'], budgetUsd: 0.05, totalBudgetUsd: 0.5, spentBeforeUsd: 0.5 - one - 0.0002, models: { fake: cheap } });
  check('the total ceiling: a run stops before a call whose reserved cost is more than what\'s left overall', calls === 1 && tr.runs[1].outcome === 'skipped-budget' && tr.meta.stoppedForBudget && tr.meta.spentBeforeUsd + tr.meta.spentUsd <= 0.5, tr.meta);
  check('…and a ceiling already used up refuses to start', /used up/.test(await fails(() => run.evaluate({ ...base, live: true, budgetUsd: 0.05, totalBudgetUsd: 0.5, spentBeforeUsd: 0.5, models: { fake: cheap } }))));
  // The original reply and the corrected proposal are scored separately.
  const sloppyProvider = require('http').createServer((req, res) => {
    let b = ''; req.on('data', c => { b += c; });
    req.on('end', () => {
      const c = JSON.parse(JSON.parse(b).messages[1].content.replace(/^[^\n]*\n/, ''));
      const ids = c.tasks.filter(x => !x.done).map(x => x.id);
      const content = c.date === '2026-11-10' && c.now === '14:30' ? JSON.stringify({ rest: false, priorities: ids.map(id => ({ taskId: id, minutes: 45, start: '16:00' })), explanation: 'Do both.', missing: [] })
        : JSON.stringify({ rest: false, priorities: [{ taskId: 'not-a-task', minutes: 10, start: null }], explanation: 'x', missing: [] });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(c.now === '09:00' ? { choices: [{ message: { content: '{"rest": false, "priorities": [' }, finish_reason: 'length' }], usage: { prompt_tokens: 900, completion_tokens: 600 } }
        : { choices: [{ message: { content }, finish_reason: 'stop' }], usage: { prompt_tokens: 900, completion_tokens: 60 } }));
    });
  });
  await new Promise(r => sloppyProvider.listen(0, '127.0.0.1', r));
  const sloppyModel = { ...cheap, baseUrl: `http://127.0.0.1:${sloppyProvider.address().port}` };
  tr = await run.evaluate({ ...base, live: true, repeats: 1, scenarioIds: ['s08-after-night-shift', 's04-good-day'], budgetUsd: 0.05, models: { fake: sloppyModel } });
  const s08 = tr.runs.find(x => x.scenario === 's08-after-night-shift'), s04 = tr.runs.find(x => x.scenario === 's04-good-day');
  check('the original reply is scored as the model sent it (too long, on top of the appointment)…', s08.outcome === 'ok' && s08.expectRaw.fitsTime === false && s08.expectRaw.avoidsBusy === false && s08.violations.includes('time-conflict') && s08.violations.includes('too-many'), s08);
  check('…the corrected proposal separately (what you\'d see), with the corrections listed', s08.expectFinal.fitsTime === true && s08.expectFinal.avoidsBusy === true && s08.adjusted.length > 0 && s08.violationDetails.some(d => /^time-conflict: /.test(d)), s08);
  check('a reply cut off at the length limit: unsuccessful ("truncated"), no expectations met, nothing saved', s04.outcome === 'error' && /^truncated/.test(s04.error) && s04.finishReason === 'length' && s04.savedSafely === null && Object.values(s04.expectRaw).every(v => v === false) && s04.outputTokens === 600, s04);
  tr = await run.evaluate({ ...base, live: true, repeats: 2, scenarioIds: ['s04-good-day'], budgetUsd: 0.05, stopOnFailure: true, models: { fake: sloppyModel } });
  check('--stop-on-failure: after an unsuccessful generation, that model isn\'t called again in the run', tr.runs.length === 2 && tr.runs[0].outcome === 'error' && tr.runs[1].outcome === 'skipped-failure');
  const report = run.summary(tr) + run.calls(tr);
  check('the report lists unsuccessful generations and every call (finish reason, tokens incl. reasoning)', /## Unsuccessful generations/.test(report) && /truncated/.test(report) && /\| length \|/.test(report) && /not called \(after a failure\)/.test(report));
  sloppyProvider.close();
  // No connection: a closed port (nothing listening), so every call fails to connect.
  const closed = require('http').createServer(); await new Promise(r => closed.listen(0, '127.0.0.1', r)); const deadPort = closed.address().port; await new Promise(r => closed.close(r));
  tr = await run.evaluate({ ...base, live: true, repeats: 1, scenarioIds: ['s01-energy-1', 's02-energy-2-20min', 's03-poor-sleep', 's04-good-day', 's05-day-shift-morning'], budgetUsd: 0.05, models: { fake: { ...cheap, baseUrl: `http://127.0.0.1:${deadPort}` } } });
  check('no connection: the run stops after 3 calls in a row that couldn\'t reach a provider (the rest aren\'t called or counted)', tr.meta.stoppedForConnection && tr.runs.filter(x => x.outcome === 'error').length === 3 && tr.runs.filter(x => x.outcome === 'skipped-connection').length === 2 && Math.abs(tr.meta.spentUsd - tr.runs.reduce((a, x) => a + (x.reservedUsd || 0), 0)) < 1e-6, tr.meta);
  check('…and says why each failed (e.g. ECONNREFUSED), to tell this side\'s network from the provider\'s', tr.runs[0].error === 'network' && /ECONNREFUSED/.test(tr.runs[0].errorDetail || ''), tr.runs[0]);
  check('calls that reported no usage keep their reservation, shown apart from the estimated cost (until provider billing resolves them)', tr.meta.usageUsd === 0 && tr.meta.reservedUsd > 0 && /Reserved for 3 call\(s\) that reported no usage, and kept until provider billing shows what they cost/.test(run.summary(tr)));
  // The tone filter flags a word wherever it is; without the original wording, a flag stays unverified.
  const toneRun = await run.evaluate({ ...base, live: false, budgetUsd: null, repeats: 1, scenarioIds: ['s01-energy-1'], modelIds: ['m'], models: { m: { label: 'Mock', provider: 'mock', model: 'mock:sloppy', priceInPerMTok: 0, priceOutPerMTok: 0 } } });
  const toned = toneRun.runs[0];
  check('the model\'s original reply is kept with the results (made-up scenarios only), so flags can be checked', typeof toned.originalReply === 'string' && toned.originalReply.length > 20 && toned.violations.includes('pressure-language') && /tone flag: ".+" \(original kept in runs\.json\)/.test(run.calls(toneRun)));
  const oldRun = JSON.parse(JSON.stringify(toneRun)); oldRun.runs[0].originalReply = null;
  check('…and a tone flag without the original wording is marked unverified (as in results saved before it was kept)', /tone flag: ".+" \(unverified: original wording not kept\)/.test(run.calls(oldRun)) && /1 of these 1 flag\(s\) are unverified/.test(run.summary(oldRun)) && /tone flag, unverified/.test(run.review(oldRun)));
  const est = run.estimate({ ...base, repeats: 3, scenarioIds: null, models: { q: { ...cheap, priceTierMaxInputTokens: 256000 }, g: { ...cheap, maxOutputTokens: 2048, priceInPerMTok: 0.15, priceOutPerMTok: 0.5 } }, modelIds: ['q', 'g'] });
  check('the estimate: from the real prompts, each model\'s reply cap (reasoning included), with a margin on top — and says it\'s not a guarantee', /\| 60 \|/.test(est) && /2048/.test(est) && /further 25%/.test(est) && /not a guarantee/.test(est), est);
  const mockRun = await run.evaluate({ ...base, live: false, budgetUsd: null, modelIds: ['m'], models: { m: { label: 'Mock', provider: 'mock', model: 'mock:good', priceInPerMTok: 0, priceOutPerMTok: 0 } } });
  check('a mock run: 20 scenarios × 3 repeats, every reply usable, and saving each changed only today\'s plan', mockRun.runs.length === 60 && mockRun.runs.every(r => r.outcome === 'ok' && r.savedSafely === true));
  fakeProvider.close();

  const { pass, fail } = summary();
  console.log(`\n${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
})().catch(e => { console.log('HARNESS:', e); process.exit(2); });
