// Browser journey in tests/run.sh's throwaway profile; never the user's plan or account.
const T = require('./cdp.js');
const fs = require('fs');
const { ev, click, exists, text, data, sleep, check } = T;
const go = async hash => { T.setUrl('app/dist/index.html#' + hash); await T.openAt(2026, 10, 5, 10); await sleep(300); };
async function fill(sel, value) {
  await ev(`(() => { const e = document.querySelector(${JSON.stringify(sel)}); const p = e instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : e instanceof HTMLSelectElement ? HTMLSelectElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(p, 'value').set.call(e, ${JSON.stringify(value)}); e.dispatchEvent(new Event('input', { bubbles: true })); e.dispatchEvent(new Event('change', { bubbles: true })); e.blur(); })()`); await sleep(80);
}
(async () => {
  await T.connect(); await go('study'); await ev('localStorage.clear()'); await go('study');
  check('cybersecurity is available before setting up a roadmap', await exists('a[href="#study/cybersecurity"]'));
  await click('a[href="#study/cybersecurity"]'); await sleep(400);
  check('the foundation map renders 14 modules', await ev(`document.querySelectorAll('section[aria-label="Modules on your learning map"] > a').length`) === 14);
  await click('[data-action=cyber-import]'); await sleep(300);
  let saved = await data(), before = JSON.stringify(saved.study.stages);
  check('the chosen curriculum becomes real Study courses', saved.study.stages.flatMap(s => s.courses).length === 14);
  await click('[data-action=cyber-import]'); await sleep(200);
  check('repeat import preserves the same roadmap', JSON.stringify((await data()).study.stages) === before);
  for (const id of ['learning-evidence', 'authorised-scope', 'lab-isolation', 'technical-notes', 'help-and-debugging']) {
    await go('study/cybersecurity/lesson.' + id);
    check('lesson renders its real activities: ' + id, (await text('#app')).includes('Completion criteria') && await exists('a[href="#study/cybersecurity/exercise.' + id + '"]'));
  }
  await go('study/cybersecurity/lesson.learning-evidence'); await click('.cyber-workshop button'); await sleep(200);
  check('a curriculum lesson starts the existing Study timer', (await ev('location.hash')) === '#study/session' && (await data()).study.sessions[0].taskId === 'cyber:1:lesson.learning-evidence');
  check('the timer links back to the actual lesson', await exists('a[href="#study/cybersecurity/lesson.learning-evidence"]'));
  await go('study/cybersecurity/assessment.learning-evidence-check');
  check('answer keys are absent before an attempt', !(await text('#app')).includes('No; performance needs observable evidence.'));
  await click('[data-action=cyber-begin]'); await sleep(150); await click('[data-action=cyber-submit]'); await sleep(100);
  check('empty submission is rejected accessibly', await exists('[role=alert]'));
  await fill('#cyberVariant', 'First independent recall');
  const q = await ev('[...document.querySelectorAll("textarea[id^=assessment]")].map(e => e.id)');
  for (const id of q) await fill(`[id="${id}"]`, 'My own answer before the guide.');
  await fill('#cyberEvidence', 'I explained the difference between reading and observable output.');
  await fill('#cyberResume', 'Try a fresh example tomorrow.'); await fill('#cyberCritical', 'true');
  await go('study/cybersecurity/assessment.learning-evidence-check');
  check('draft evidence and answers survive reload', (await ev('document.querySelector("#cyberEvidence").value')).includes('observable output') && (await data()).cybersecurity.attempts[0].answers[q[0]].includes('My own answer'));
  await ev(`window.practiceRealSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function(k, v) { if (k === 'myday.data.v4') throw new DOMException('Test quota', 'QuotaExceededError'); return window.practiceRealSetItem.call(this, k, v); };`);
  await click('[data-action=cyber-submit]'); await sleep(150);
  check('a rejected notebook save leaves the draft editable and reports the failure', await exists('#cyberEvidence') && (await text('[role=alert]')).includes('Could not save') && !(await data()).cybersecurity.attempts[0].submittedAt);
  await ev('Storage.prototype.setItem = window.practiceRealSetItem; delete window.practiceRealSetItem');
  await click('[data-action=cyber-submit]'); await sleep(250);
  check('submission retains real evidence and remains unverified', (await data()).cybersecurity.attempts[0].submittedAt && (await data()).cybersecurity.attempts[0].verified === false);
  await click('[data-action=cyber-answers]'); await sleep(300);
  check('the guide is released after submission on explicit request', (await text('#app')).includes('No; performance needs observable evidence.'));
  await click('[data-action=cyber-begin]'); await sleep(150);
  check('retry keeps the previous submitted attempt', (await data()).cybersecurity.attempts.length === 2 && (await data()).cybersecurity.attempts[0].submittedAt);
  await go('study/cybersecurity/lab.learning-lab-guided');
  check('the learning lab links to an actual platform assignment and in-app practice', await exists('a[href="#study/cybersecurity/assignment.thm-start"]') && await exists('a[href="#study/cybersecurity/interactive.scope"]'));
  await go('study/cybersecurity/practice'); await fill('#practiceAccess', 'local');
  check('the practice shelf can show only its three in-app activities', await ev(`document.querySelectorAll('.cyber-workshop a[href*="/interactive."]').length`) === 3 && !(await text('#app')).includes('TryHackMe:'));
  await fill('#practiceAccess', 'all'); await fill('#practiceSearch', 'tryhackme');
  check('provider search finds specific TryHackMe assignments', await ev(`document.querySelectorAll('.cyber-workshop a[href*="/assignment.thm-"]').length`) === 3);
  await go('study/cybersecurity/assignment.thm-network'); await click('[data-action=practice-begin]'); await sleep(100);
  check('external links use the verified room and open separately', await ev(`(() => { const a = document.querySelector('[data-action=practice-open]'); return a.href === 'https://tryhackme.com/room/whatisnetworking' && a.target === '_blank' && a.rel.includes('noopener'); })()`));
  check('starting external work leaves it incomplete', (await data()).cybersecurity.attempts.find(a => a.activityId === 'assignment.thm-network').submittedAt === null);
  await fill('#practiceEvidence', 'Tasks 1–4: I compared addresses and described what the simulated ping establishes.'); await fill('#practiceOutcome', 'partial'); await fill('#practiceCritical', 'true');
  await go('study/cybersecurity/assignment.thm-network');
  check('external progress and notes resume after reload', (await ev('document.querySelector("#practiceOutcome").value')) === 'partial' && (await ev('document.querySelector("#practiceEvidence").value')).includes('Tasks 1–4'));
  await fill('#practiceOutcome', 'completed');
  await ev(`window.practiceRealSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function(k, v) { if (k === 'myday.data.v4') throw new DOMException('Test quota', 'QuotaExceededError'); return window.practiceRealSetItem.call(this, k, v); };`);
  await click('[data-action=practice-submit]'); await sleep(150);
  check('a rejected external check-in does not claim completion', await exists('#practiceOutcome') && (await text('[role=alert]')).includes('Could not save') && !(await data()).cybersecurity.attempts.find(a => a.activityId === 'assignment.thm-network').submittedAt);
  await ev('Storage.prototype.setItem = window.practiceRealSetItem; delete window.practiceRealSetItem');
  await click('[data-action=practice-submit]'); await sleep(180);
  check('check-in is explicitly self-reported and retained', (await text('#app')).includes('provider progress not verified') && (await data()).cybersecurity.attempts.find(a => a.activityId === 'assignment.thm-network').submittedAt);
  await go('study/cybersecurity/assignment.thm-start'); await click('[data-action=practice-begin]'); await sleep(100);
  await fill('#practiceOutcome', 'blocked'); await fill('#practiceEvidence', 'The provider machine was unavailable today.'); await fill('#practiceCritical', 'false'); await click('[data-action=practice-submit]'); await sleep(180);
  check('access problems save without a false completion and offer an alternative', (await text('#app')).includes('Could not access') && await exists('a[href="#study/cybersecurity/interactive.scope"]'));
  await go('study/cybersecurity/interactive.scope'); await click('[data-action=practice-begin]'); await sleep(100);
  for (const [id, value] of Object.entries({ 'scope-one': 'proceed', 'scope-two': 'proceed', 'scope-three': 'stop', 'scope-four': 'clarify' })) await fill('#' + id, value);
  await fill('#practiceEvidence', 'I paused when the permitted time window ended.'); await fill('#practiceCritical', 'true'); await click('[data-action=practice-submit]'); await sleep(180);
  check('scope decisions produce feedback including a wrong answer', (await text('#app')).includes('3 of 4 checks matched') && (await text('#app')).includes('Reachability does not extend authorisation'));
  await go('study/cybersecurity/interactive.network'); await click('[data-action=practice-begin]'); await sleep(100); await click('[data-action=network-run]'); await sleep(100);
  check('the simulated fault produces an observable failure trace', (await text('[aria-label="Connection trace"]')).includes('Name lookup failed'));
  await fill('#networkDns', 'available');
  check('changing a network setting clears stale feedback', !await exists('[aria-label="Connection trace"]'));
  await click('[data-action=network-run]'); await sleep(100);
  check('repairing DNS changes the simulation outcome', (await text('[aria-label="Connection trace"]')).includes('Website reached'));
  await fill('#practiceEvidence', 'Restoring the local resolver allowed name lookup, routing and TCP 443. It does not prove security.'); await fill('#practiceCritical', 'true');
  await go('study/cybersecurity/interactive.network');
  check('network settings and last run survive reload', (await text('[aria-label="Connection trace"]')).includes('Website reached'));
  await click('[data-action=practice-submit]'); await sleep(180);
  check('network result and explanation become notebook history', (await text('#app')).includes('1 of 1 checks matched'));
  await go('study/cybersecurity/interactive.auth-logs'); await click('[data-action=practice-begin]'); await sleep(100);
  await fill('#logFilter', 'auth-025');
  check('raw log filtering exposes a repeated event without hiding it from counts', (await text('#app')).includes('Showing 2 of 33 raw rows'));
  for (const [id, value] of Object.entries({ valid: '30', failures: '6', invalid: '2', duplicate: '1' })) await fill('#log-' + id, value);
  await fill('#practiceEvidence', 'auth-023 to auth-028 deserve review; failures then success could be misuse or a legitimate retry. Ask for endpoint evidence.'); await fill('#practiceCritical', 'true'); await click('[data-action=practice-submit]'); await sleep(180);
  check('log checks match the fixture and retain uncertainty about compromise', (await text('#app')).includes('4 of 4 checks matched') && (await text('#app')).includes('does not establish who acted'));
  const evidence = JSON.stringify((await data()).cybersecurity);
  T.setUrl('index.html#study'); await T.openAt(2026, 10, 5); await click('#themeBtn'); await sleep(200);
  check('classic MyDay preserves the new evidence section', JSON.stringify((await data()).cybersecurity) === evidence);
  await T.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  for (const hash of ['study/cybersecurity', 'study/cybersecurity/module.learning-lab', 'study/cybersecurity/lesson.learning-evidence', 'study/cybersecurity/assessment.learning-evidence-check', 'study/cybersecurity/toolkit', 'study/cybersecurity/practice', 'study/cybersecurity/assignment.thm-network', 'study/cybersecurity/interactive.network', 'study/cybersecurity/interactive.auth-logs']) {
    await go(hash);
    check('phone layout fits: ' + hash, !(await ev('document.documentElement.scrollWidth > innerWidth')));
  }
  await go('study/cybersecurity');
  check('workshop navigation offers 44-pixel touch targets', await ev(`[...document.querySelectorAll('nav[aria-label="Cybersecurity"] a')].every(a => a.getBoundingClientRect().height >= 44)`));
  fs.writeFileSync('/tmp/myday-cybersecurity-mobile.png', Buffer.from((await T.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data, 'base64'));
  await go('study/cybersecurity/interactive.network'); await click('[data-action=practice-begin]'); await sleep(100);
  await ev(`document.querySelector('#practice-attempt-title').scrollIntoView({block:'start'})`);
  fs.writeFileSync('/tmp/myday-practice-mobile.png', Buffer.from((await T.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data, 'base64'));
  check('interactive controls offer 44-pixel touch targets', await ev(`[...document.querySelectorAll('.cyber-workshop select, .cyber-workshop button')].every(a => a.getBoundingClientRect().height >= 44)`));
  await go('study/cybersecurity/interactive.auth-logs'); await click('[data-action=practice-begin]'); await sleep(100);
  check('raw log table scrolls inside the phone screen', !(await ev('document.documentElement.scrollWidth > innerWidth')) && await ev(`(() => { const table = document.querySelector('[aria-label="Synthetic sign-in events"]'); return table.scrollWidth > table.clientWidth; })()`));
  await T.send('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 });
  await fill('#log-valid', '30'); await fill('#practiceEvidence', 'Offline draft stays on this device.');
  check('in-app practice can save a draft without a network connection', (await data()).cybersecurity.attempts.find(a => a.activityId === 'interactive.auth-logs' && !a.submittedAt).answers['assessment.practice.valid'] === '30');
  await T.send('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: 0, uploadThroughput: 0 });
  await T.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  await go('study/cybersecurity');
  fs.writeFileSync('/tmp/myday-cybersecurity-desktop.png', Buffer.from((await T.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data, 'base64'));
  await ev(`(() => { const d = JSON.parse(localStorage.getItem('myday.data.v4')); d.settings.theme = 'light'; localStorage.setItem('myday.data.v4', JSON.stringify(d)); })()`);
  await go('study/cybersecurity');
  fs.writeFileSync('/tmp/myday-cybersecurity-light.png', Buffer.from((await T.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data, 'base64'));
  await go('study/cybersecurity/practice');
  fs.writeFileSync('/tmp/myday-practice-desktop.png', Buffer.from((await T.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })).data, 'base64'));
  await go('study/cybersecurity/%ZZ'); check('a malformed link recovers without a blank page', (await text('#app')).includes('Cybersecurity workshop'));
  await go('study/cybersecurity/lesson.no-such-lesson'); check('a missing lesson has a return link', (await text('#app')).includes('This learning page isn’t here'));
  T.setUrl('aimock/index.html#study/cybersecurity/lesson.learning-evidence'); await T.openAt(2026, 10, 5); await sleep(300);
  const beforeAI = JSON.stringify((await data()).cybersecurity);
  await fill('#cyberTutorQuestion', 'What counts as evidence?'); await click('[data-action=cyber-ask]'); await sleep(850);
  check('optional tutor renders a checked explanation in practice mode', (await text('#app')).includes('Rules-only practice response'));
  check('AI explanation does not change attempts or scores', JSON.stringify((await data()).cybersecurity) === beforeAI);
  const s = T.summary(); console.log(`\n${s.pass} passed, ${s.fail} failed`); process.exit(s.fail ? 1 : 0);
})().catch(e => { console.error('HARNESS', e); process.exit(1); });
