// Curriculum import, evidence and privacy contracts on the production code, with disposable data.
const fs = require('fs'), os = require('os'), path = require('path');
const { pathToFileURL } = require('url');
const { check, summary } = require('./cdp.js');
const ROOT = process.env.MYDAY_ROOT || path.resolve(__dirname, '..');
const same = require('node:util').isDeepStrictEqual;
(async () => {
  const { bundle } = await import(pathToFileURL(path.join(ROOT, 'ai-eval/build.mjs')).href);
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'myday-cyber-rules-'));
  const files = ['app/src/study/cybersecurity/catalogue', 'app/src/study/cybersecurity/learning', 'app/src/study/cybersecurity/practiceCatalogue', 'app/src/study/cybersecurity/practiceRules', 'app/src/study/cybersecurity/tutorReply', 'app/src/data/cybersecurity/normalize', 'app/src/data/cybersecurity/types', 'app/src/data/normalize', 'app/src/sync/records', 'app/src/study/route', 'supabase/functions/_shared/ai/tutor', 'supabase/functions/_shared/ai/prompt'];
  fs.writeFileSync(path.join(dir, 'kit.ts'), files.map(f => `export * from ${JSON.stringify(path.join(ROOT, f))};`).join('\n'));
  const C = await import(pathToFileURL(await bundle(path.join(dir, 'kit.ts'), path.join(dir, 'out'))).href);
  const d = C.freshState();
  d.study.stages = [{ id: 'my-stage', title: 'Personal studies', courses: [{ id: 'mine', title: 'Spanish', url: '', minutes: 20, listId: null, archived: false, modules: [] }] }];
  const untouched = JSON.stringify({ lists: d.lists, days: d.days, notes: d.notes, projects: d.projects, course: d.study.stages[0].courses[0] });
  check('the core path adds 14 courses', C.importPath(d, 'path.core') === 14);
  check('import does not change existing content or Today', untouched === JSON.stringify({ lists: d.lists, days: d.days, notes: d.notes, projects: d.projects, course: d.study.stages[0].courses[0] }));
  const stages = JSON.stringify(d.study.stages);
  check('importing again is a no-op for the roadmap', C.importPath(d, 'path.core') === 0 && stages === JSON.stringify(d.study.stages));
  for (const p of C.curriculum.paths) C.importPath(d, p.id);
  const courses = d.study.stages.flatMap(s => s.courses), tasks = courses.flatMap(c => c.modules.flatMap(m => m.sections.flatMap(s => s.tasks)));
  check('all paths share the same 27 modules and 146 stable lesson IDs', courses.length === 28 && tasks.length === 146 && new Set(tasks.map(t => t.id)).size === 146);
  check('all imported lesson links resolve', tasks.every(t => C.lessons.has(C.lessonFromTask(t.id))));
  check('imported roadmap survives normalisation unchanged', same(C.normalize(d).study, d.study));
  const moved = C.freshState(); C.importPath(moved, 'path.core');
  const coursesToMove = moved.study.stages[0].courses;
  const movedTask = coursesToMove[0].modules[0].sections[0].tasks.shift();
  coursesToMove[1].modules[0].sections[0].tasks.push(movedTask);
  coursesToMove.shift(); C.importPath(moved, 'path.core');
  check('reimport after removing a course does not duplicate a lesson moved elsewhere', moved.study.stages.flatMap(s => s.courses).flatMap(c => c.modules.flatMap(m => m.sections.flatMap(s => s.tasks))).filter(t => t.id === movedTask.id).length === 1);
  check('malformed URI cannot crash Study', C.studyRoute('#study/cybersecurity/%ZZ').view === 'cybersecurity');
  const activity = C.activities.get('exercise.learning-evidence');
  const id = C.beginAttempt(d, activity.id), a = d.cybersecurity.attempts[0];
  check('starting twice resumes one draft', C.beginAttempt(d, activity.id) === id && d.cybersecurity.attempts.length === 1);
  check('empty work cannot be submitted', !!C.submitAttempt(d, id) && !a.submittedAt);
  Object.assign(a, { evidence: 'My actual observation, including a failed check.', inputVariant: 'scenario one', criticalPassed: true, rubricScores: [100, 100, 100, 100], assistance: 'hint' });
  check('a real assisted attempt can be submitted and its practical score is capped', C.submitAttempt(d, id) === null && C.attemptScore(a, activity) === 60);
  check('submission cannot overwrite history', !!C.submitAttempt(d, id));
  const id2 = C.beginAttempt(d, activity.id), a2 = d.cybersecurity.attempts.find(x => x.id === id2);
  Object.assign(a2, { evidence: 'I found an unresolved scope error.', inputVariant: 'scenario two', criticalPassed: false, rubricScores: [100, 100, 100, 100] });
  C.submitAttempt(d, id2);
  check('failed critical checks give 0 and the failed attempt is retained', C.attemptScore(a2, activity) === 0 && d.cybersecurity.attempts.length === 2);
  check('self-assessment cannot be promoted to verified mastery through import', C.cleanAttempt({ ...a, verified: true, assessor: 'ai' }).verified === false);
  check('historical rubric versions are not rescored against current content', C.attemptScore({ ...a, rubricVersion: '0.9.0' }, activity) === null);
  const assessment = C.activities.get('assessment.learning-evidence-check');
  const qid = C.beginAttempt(d, assessment.id), qa = d.cybersecurity.attempts.find(x => x.id === qid);
  Object.assign(qa, { evidence: 'Baseline', inputVariant: 'first recall', criticalPassed: true });
  check('the answer attempt requires every question', !!C.submitAttempt(d, qid));
  qa.answers = Object.fromEntries(assessment.questions.map(q => [q.id, 'I do not know yet.']));
  check('honest uncertainty is accepted without an invented score', !C.submitAttempt(d, qid) && C.attemptScore(qa, assessment) === null);
  check('learner catalogue has no knowledge-check answers', !JSON.stringify(C.curriculum).includes('expected_answer'));
  check('top-level learner evidence survives save and backup normalisation', same(C.normalize(d).cybersecurity, d.cybersecurity));
  const records = C.localRecords(d), dest = C.freshState();
  for (const [k, c] of records) C.putRecord(dest, k, C.cleanRecord(k, c));
  check('preferences and every attempt survive the account round trip', same(C.normalize(dest).cybersecurity, d.cybersecurity));
  check('mismatched attempt IDs from sync are rejected', C.cleanRecord('cyber_attempt:someone-else', a) === null);
  check('malformed evidence is reported, not silently trusted', (() => { const report = { dropped: 0 }; C.normalizeCyber({ attempts: [{ bad: true }] }, report); return report.dropped === 1; })());
  const practiceData = C.freshState();
  const setAnswer = (a, key, value) => { a.answers[C.answerKey(key)] = value; };
  const start = id => { const aid = C.beginAttempt(practiceData, id); return practiceData.cybersecurity.attempts.find(a => a.id === aid); };
  const prepared = a => Object.assign(a, { evidence: 'Observed an outcome, compared a baseline, and named a limitation.', criticalPassed: true });
  check('every practice assignment resolves to an activity and real lessons', C.practiceActivities.every(p => C.activities.has(p.id) && p.lessonIds.every(id => C.lessons.has(id))));
  check('every external assignment has an HTTPS provider and a working fallback', C.practiceActivities.filter(p => p.kind === 'external').every(p => p.url.startsWith('https://') && C.activities.has(p.fallbackId)));
  check('the learning lab offers concrete starting activities', C.relatedPractice('lab.learning-lab-guided').some(p => p.id === 'assignment.thm-start'));
  const ext = prepared(start('assignment.thm-network'));
  check('starting an external assignment does not complete it', !ext.submittedAt && !C.answer(ext, 'outcome'));
  check('external drafts resume instead of duplicating records', start(ext.activityId).id === ext.id);
  check('saving requires an explicit external outcome', !!C.submitAttempt(practiceData, ext.id));
  setAnswer(ext, 'outcome', 'completed'); ext.criticalPassed = false;
  check('completion cannot conceal an unresolved scope check', !!C.submitAttempt(practiceData, ext.id));
  setAnswer(ext, 'outcome', 'blocked');
  check('blocked access can be recorded honestly without passing scope', C.submitAttempt(practiceData, ext.id) === null && ext.verified === false);
  const completed = prepared(start(ext.activityId)); setAnswer(completed, 'outcome', 'completed');
  check('an explicit check-in records completion without changing Study tasks', C.submitAttempt(practiceData, completed.id) === null && practiceData.study.stages.length === 0 && C.attemptScore(completed, C.activities.get(completed.activityId)) === null);
  const scope = prepared(start('interactive.scope'));
  check('scope practice needs every decision', !!C.submitAttempt(practiceData, scope.id));
  C.scopeCases.forEach(q => setAnswer(scope, q.id, q.correct)); setAnswer(scope, 'scope-two', 'proceed');
  check('incorrect scope choices are saved as learning attempts', !C.submitAttempt(practiceData, scope.id) && C.practiceChecks(scope, C.practiceById.get(scope.activityId)).filter(c => c.passed).length === 3);
  const net = prepared(start('interactive.network'));
  check('network practice starts with a reproducible failing scenario', !C.simulateNetwork(C.networkConfig(net)).connected && !C.answer(net, 'run'));
  check('unrun network settings cannot be submitted', !!C.submitAttempt(practiceData, net.id));
  for (const id of Object.keys(C.networkScenarios)) {
    C.setScenario(net, id);
    check('the ' + id + ' scenario fails at the expected step', !C.simulateNetwork(C.networkConfig(net)).connected);
    setAnswer(net, 'dns', 'available'); setAnswer(net, 'gateway', '10.20.0.1'); setAnswer(net, 'https', 'allow');
    check('repairing the ' + id + ' scenario reaches the website', C.simulateNetwork(C.networkConfig(net)).connected);
  }
  setAnswer(net, 'run', C.networkSignature(C.networkConfig(net))); setAnswer(net, 'https', 'block');
  check('changing settings invalidates the previous simulation run', !!C.submitAttempt(practiceData, net.id));
  setAnswer(net, 'run', C.networkSignature(C.networkConfig(net)));
  check('a failed simulation is retained with its inputs', !C.submitAttempt(practiceData, net.id) && !C.practiceChecks(net, C.practiceById.get(net.activityId))[0].passed);
  const log = prepared(start('interactive.auth-logs')), parsed = C.analyseAuthRows(C.authRows);
  check('fixture parsing excludes invalid rows before deduplicating', same([C.authRows.length, parsed.valid.length, parsed.failures.length, parsed.invalid.length, parsed.duplicate.length], [33, 30, 6, 2, 1]));
  check('fixture timestamps retain timezone offsets', Date.parse(parsed.valid[0][1]) === Date.parse('2026-01-15T10:01:00Z'));
  const invalidCopy = [...C.authRows[0]]; invalidCopy[1] = 'bad';
  check('an invalid first occurrence cannot suppress a later valid event', C.analyseAuthRows([invalidCopy, C.authRows[0]]).valid.length === 1);
  for (const [key, value] of Object.entries({ valid: '30', failures: '6', invalid: '2', duplicate: '1' })) setAnswer(log, key, value);
  setAnswer(log, 'valid', '-1'); check('log counts reject invalid numeric input', !!C.submitAttempt(practiceData, log.id)); setAnswer(log, 'valid', '30');
  check('correct log counts match checks but never verify mastery', !C.submitAttempt(practiceData, log.id) && C.practiceChecks(log, C.practiceById.get(log.activityId)).every(c => c.passed) && log.verified === false);
  const freshDraft = start('interactive.auth-logs'); freshDraft.rubricVersion = 'practice-0.9.0';
  check('a changed practice version preserves the old draft and creates a new one', start('interactive.auth-logs').id !== freshDraft.id && practiceData.cybersecurity.attempts.includes(freshDraft));
  const practiceDestination = C.freshState();
  for (const [k, c] of C.localRecords(practiceData)) C.putRecord(practiceDestination, k, C.cleanRecord(k, c));
  check('external and interactive inputs survive normalisation, backup and account records', same(C.normalize(practiceData).cybersecurity, practiceData.cybersecurity) && same(C.normalize(practiceDestination).cybersecurity, practiceData.cybersecurity));
  const ctx = { version: 1, action: 'tutor', curriculumVersion: '1.0.0', lessonId: 'lesson.learning-evidence', question: 'Help me understand evidence.' };
  check('tutor accepts only a known version and lesson', C.checkTutorContext(ctx) && !C.checkTutorContext({ ...ctx, lessonId: '__proto__' }) && !C.checkTutorContext({ ...ctx, curriculumVersion: '2.0.0' }));
  check('tutor rejects private extra fields and oversized requests', !C.checkTutorContext({ ...ctx, notebook: 'private work' }) && !C.checkTutorContext({ ...ctx, question: 'x'.repeat(1001) }));
  const messages = C.messagesFor(ctx);
  check('tutor uses authoritative lesson context, without answer keys', messages[1].content.includes('Learning through evidence') && !messages[1].content.includes('No; performance needs observable evidence.'));
  check('a bounded response for the selected lesson is accepted', !!C.tutorReply(C.mockTutor(ctx), ctx.lessonId));
  check('wrong-lesson, score-bearing and malformed responses are refused', !C.tutorReply(C.mockTutor(ctx), 'lesson.other') && !C.tutorReply(JSON.stringify({ lessonId: ctx.lessonId, explanation: 'x', nextStep: 'x', score: 100 }), ctx.lessonId) && !C.tutorReply('bad', ctx.lessonId));
  const { handle } = await import(pathToFileURL(path.join(ROOT, 'supabase/functions/ai-plan/handler.ts')).href);
  let budgetCalls = 0;
  const env = { AI_PROVIDER: 'mock', AI_MODEL: 'mock:good', AI_MOCK_DELAY_MS: '0' };
  const deps = { env: k => env[k], verifyUser: async () => 'test-account', begin: async () => { budgetCalls++; return { ok: true }; }, finish: async () => {} };
  const req = c => new Request('http://test/ai-plan', { method: 'POST', headers: { Authorization: 'Bearer test.user.token' }, body: JSON.stringify({ context: c }) });
  const response = await handle(req(ctx), deps), result = await response.json();
  check('server tutor uses the authenticated, budget-limited provider path', response.status === 200 && !!C.tutorReply(result.output, ctx.lessonId) && budgetCalls === 1);
  check('unknown lessons are rejected before budget or provider use', (await handle(req({ ...ctx, lessonId: 'lesson.missing' }), deps)).status === 400 && budgetCalls === 1);
  fs.rmSync(dir, { recursive: true, force: true });
  const s = summary(); console.log(`\n${s.pass} passed, ${s.fail} failed`); process.exit(s.fail ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
